package modulo;

import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;
import java.util.UUID;
import java.util.function.Function;

import org.eclipse.jetty.client.Response;
import org.eclipse.jetty.http.HttpURI;
import org.eclipse.jetty.io.Content;
import org.eclipse.jetty.proxy.ProxyHandler;
import org.eclipse.jetty.server.Request;
import org.eclipse.jetty.server.handler.ErrorHandler;
import org.eclipse.jetty.util.Callback;

/**
 * Subclass of Jetty's proxy handler, allows us to make required modifications to the proxied request before forwarding it to the instance
 */
class ModuloProxy extends ProxyHandler.Reverse {

	public ModuloProxy( Function<Request, HttpURI> httpURIRewriter ) {
		super( httpURIRewriter );
	}

	@Override
	protected void addProxyHeaders( Request clientToProxyRequest, org.eclipse.jetty.client.Request proxyToServerRequest ) {
		super.addProxyHeaders( clientToProxyRequest, proxyToServerRequest );
		proxyToServerRequest.headers( headers -> headers.add( "x-webobjects-adaptor-version", "Modulo" ) ); // mod_WebObjects sends "Apache" here. I have no idea if that's significant, let's assume not
		proxyToServerRequest.headers( headers -> headers.add( "x-webobjects-request-id", UUID.randomUUID().toString() ) ); // Our unique ID does not match the format of the id generated by mod_WebObjects. Doesn't seem to hurt (yet) though. We'll handle it if it turns out to be a problem
		proxyToServerRequest.headers( headers -> headers.add( "x-webobjects-request-method", clientToProxyRequest.getMethod() ) ); // Why mod_WebObjects sends the request method, already an explicit part of the request, as a header as well, I have no idea. But it can't hurt emulating it

		// Determine the originating client IP. When modulo is behind another
		// reverse proxy, that proxy will have set 'x-forwarded-for' and we
		// honour it. When modulo is the front-facing server (the now-common
		// case), there is no upstream proxy, so we use the actual remote
		// address of the connection. Previously we only read x-forwarded-for,
		// which produced a null IP — and therefore no remote_addr/remote_host
		// headers at all — once modulo became the front door. // Hugi 2026-06-19
		final String forwardedFor = clientToProxyRequest.getHeaders().get( "x-forwarded-for" );
		final String clientIPAddress = forwardedFor != null ? forwardedFor : Request.getRemoteAddr( clientToProxyRequest );

		// Add the remote_addr / remote_host headers WO apps (and wonder's
		// ERXHTTPUtilities.ipAddressFromRequest) read to identify the client.
		// Both are set from the same source (the client IP), so they share a
		// single guard. They are semantically distinct — remote_addr is the IP,
		// remote_host is the reverse-DNS hostname (falling back to the IP) — but
		// we don't do reverse-DNS lookups (Apache's "HostnameLookups Off"
		// default), so both carry the IP today. If reverse-DNS is ever added,
		// remote_host gets its own derivation and would need its own guard,
		// since the lookup can fail independently of having an IP. // Hugi 2026-06-19
		if( clientIPAddress != null ) {
			proxyToServerRequest.headers( headers -> headers.add( "remote_addr", clientIPAddress ) );
			proxyToServerRequest.headers( headers -> headers.add( "remote_host", clientIPAddress ) );
		}

		// FIXME: Forward the original host authority to the upstream, emulating
		// Apache's `ProxyPreserveHost On`. WO apps (and wonder in particular)
		// look at the `host` header to derive request.serverName() and to
		// generate absolute URLs. Without this they see the upstream's
		// host:port (e.g. hz1.rebbi.is:2008) instead of what the browser asked
		// for (e.g. www.undirskriftasofnun.is). Under Apache→modulo this
		// happened to work because Apache forwarded the original Host with
		// `ProxyPreserveHost On` and that survived our second-hop rewriting.
		// We source the original authority from the request URI rather than
		// the Host header, because HTTP/2 carries it as the :authority
		// pseudo-header (no Host header) — and Jetty exposes that as the URI
		// authority. As modulo's front-facing role matures we should migrate
		// WO apps off reading `host` directly and onto the standard
		// X-Forwarded-Host / RFC 7239 Forwarded headers, and stop overriding
		// Jetty's behavior here. See issue #7. // Hugi 2026-05-22
		final String originalAuthority = clientToProxyRequest.getHttpURI().getAuthority();
		if( originalAuthority != null ) {
			proxyToServerRequest.headers( headers -> headers.put( org.eclipse.jetty.http.HttpHeader.HOST, originalAuthority ) );
		}

		// By default, Jetty will add itself to the list of user agents on the forwarded request (meaning the user-agent header contains multiple values which may confuse some apps)
		// CHECKME: This really just corrects a mistake made by ourselves so this feels hacky. Ideally, we'd instruct Jetty to never modify the user-agent header in the first place // Hugi 2025-05-07
		final String clientUserAgent = clientToProxyRequest.getHeaders().get( "user-agent" );
		proxyToServerRequest.headers( headers -> headers.put( "user-agent", clientUserAgent ) );
	}

	/**
	 * TODO: Keep track of proxying errors
	 */
	@Override
	protected void onServerToProxyResponseFailure( Request clientToProxyRequest, org.eclipse.jetty.client.Request proxyToServerRequest, Response serverToProxyResponse, org.eclipse.jetty.server.Response proxyToClientResponse, Callback proxyToClientCallback, Throwable failure ) {

		// FIXME: Mark the request so we can identify the error that occurred during error handling and return an appropriate response. Probably lame // Hugi 2025-10-12
		clientToProxyRequest.setAttribute( "modulo-error", "onServerToProxyResponseFailure" );

		super.onServerToProxyResponseFailure( clientToProxyRequest, proxyToServerRequest, serverToProxyResponse, proxyToClientResponse, proxyToClientCallback, failure );
	}

	/**
	 * Generates an error response
	 *
	 * FIXME: Work in progress, currently only generates a little experimental custom message for failure when contacting the remote application // Hugi 2025-10-12
	 */
	public static class ModuloErrorHandler extends ErrorHandler {

		@Override
		public boolean handle( Request request, org.eclipse.jetty.server.Response response, Callback callback ) throws Exception {

			final String moduloError = (String)request.getAttribute( "modulo-error" );

			switch( moduloError ) {
				case "onServerToProxyResponseFailure" -> {
					// HTTP status returned from server
					final int status = (int)request.getAttribute( ErrorHandler.ERROR_STATUS );

					// Error messageg generated by the proxy
					final String errorMessage = (String)request.getAttribute( ErrorHandler.ERROR_MESSAGE );

					// Eception that occurred (probably null for most cases, since a timeout/connection error is more likely than an internal error)
					final Throwable exception = (Throwable)request.getAttribute( ErrorHandler.ERROR_EXCEPTION );

					final Object exceptionClassName = exception != null ? exception.getClass().getName() : "[No further exception information available]";

					final String message = "Error contacting remote app. %s %s. %s".formatted( status, errorMessage, exceptionClassName );
					final byte[] content = message.getBytes( StandardCharsets.UTF_8 );
					final Content.Source cs = Content.Source.from( new ByteArrayInputStream( content ) );
					response.getHeaders().put( "content-length", String.valueOf( content.length ) );
					Content.copy( cs, response, callback );
					return false;
				}
				default -> {
					return super.handle( request, response, callback );
				}
			}
		}
	}
}